/*
 * Copyright (C) 2026 Kamil Lulko <kamil.lulko@gmail.com>
 *
 * This file is part of NNAGA.
 *
 * NNAGA is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * NNAGA is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with NNAGA. If not, see <https://www.gnu.org/licenses/>.
 */

package com.vibes.dsp.engine

import android.app.PendingIntent
import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.content.IntentFilter
import android.hardware.usb.UsbConstants
import android.hardware.usb.UsbDevice
import android.hardware.usb.UsbDeviceConnection
import android.hardware.usb.UsbManager
import android.os.Build
import android.util.Log
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlinx.coroutines.Job
import kotlinx.coroutines.withContext
import kotlinx.coroutines.delay
import kotlinx.coroutines.ensureActive
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlin.coroutines.coroutineContext
import kotlin.coroutines.resume
import java.util.concurrent.atomic.AtomicReference

data class DirectUsbDeviceOption(
    val id: Int,
    val name: String,
    val vendorId: Int,
    val productId: Int,
    internal val device: UsbDevice
)

data class DirectUsbFormat(
    val sampleRate: Int,
    val bits: Int,
    val subslotBytes: Int,
    val channels: Int = 2
) {
    val label: String
        get() = "${sampleRate} Hz · $bits-bit" +
            if (channels == 2) "" else " · $channels channels"
}

data class DirectUsbCalibrationAggregate(
    val attemptedRuns: Int,
    val successfulRuns: Int,
    val averageLatencyFrames: Double,
    val averageLatencyMilliseconds: Double,
    val score: Int
)

data class DirectUsbAutoCalibrationResult(
    val primaryProfiles: List<DirectUsbCalibrationProfile>,
    val extendedProfiles: List<DirectUsbCalibrationProfile>,
    val selectedPrimary: DirectUsbCalibrationProfile?,
    val selectedExtended: DirectUsbCalibrationProfile?,
    val finalProfile: DirectUsbCalibrationProfile?,
    val success: Boolean,
    val message: String
)

data class DirectUsbCalibrationProfile(
    val id: String,
    val format: DirectUsbFormat,
    val bufferFrames: Int,
    val periodMultiplier: Int,
    val bufferConfig: DirectUsbBufferConfig,
    val experimental: Boolean,
    val ranAtEpochMs: Long,
    val started: Boolean,
    val stable: Boolean,
    val failure: String?,
    val latencyFrames: Long,
    val latencyMilliseconds: Double,
    val xruns: Long,
    val deadlineMisses: Long,
    val transferErrors: Long,
    val deviceMinimumFrames: Int = 0,
    val dangerous: Boolean = false,
    val extended: Boolean = false,
    val label: String = "",
    val autoGenerated: Boolean = false,
    val attemptedRuns: Int = 1,
    val successfulRuns: Int = if (started) 1 else 0,
    val score: Int = 0
)

fun scoreAutoCalibrationProfileList(profiles: List<DirectUsbCalibrationProfile>): List<DirectUsbCalibrationProfile> {
    val stable = profiles.filter { it.stable }
    if (stable.isEmpty()) return profiles.map { it.copy(score = 0) }
    val minLatency = stable.minOf { it.latencyMilliseconds }
    val minBuffer = stable.minOf { it.bufferFrames }
    return profiles.map { profile ->
        profile.copy(score = if (!profile.stable) 0 else
            4 + (if (profile.latencyMilliseconds == minLatency) 2 else 0) +
                (if (profile.bufferFrames == minBuffer) 1 else 0))
    }
}

fun scoreAutoCalibrationProfiles(profiles: List<DirectUsbCalibrationProfile>): DirectUsbCalibrationProfile? =
    scoreAutoCalibrationProfileList(profiles).filter { it.stable }
        .sortedWith(compareByDescending<DirectUsbCalibrationProfile> { it.score }
            .thenBy { it.latencyMilliseconds }.thenBy { it.bufferFrames }.thenBy { it.id })
        .firstOrNull()
data class DirectUsbCalibrationCandidate(
    val bufferFrames: Int,
    val periodMultiplier: Int
)

/**
 * Candidate order is ascending buffer frames, then ascending multiplier.
 * Once a candidate is stable, all later candidates for that format are skipped.
 */
fun shouldAttemptDirectUsbCalibrationCandidate(
    candidate: DirectUsbCalibrationCandidate,
    stableCandidate: DirectUsbCalibrationCandidate?,
    stopAfterFirstStable: Boolean = true
): Boolean {
    if (!stopAfterFirstStable || stableCandidate == null) return true
    return candidate.bufferFrames < stableCandidate.bufferFrames ||
        (candidate.bufferFrames == stableCandidate.bufferFrames &&
            candidate.periodMultiplier < stableCandidate.periodMultiplier)
}
/**
 * Returns the candidates evaluated for each format, stopping independently after
 * the first stable candidate for that format.
 */
fun sequenceDirectUsbCalibrationCandidates(
    formats: List<DirectUsbFormat>,
    bufferFrames: Iterable<Int>,
    periodMultipliers: Iterable<Int>,
    isStable: (DirectUsbFormat, DirectUsbCalibrationCandidate) -> Boolean
): List<Pair<DirectUsbFormat, DirectUsbCalibrationCandidate>> {
    val frames = bufferFrames.sorted()
    val multipliers = periodMultipliers.sorted()
    return buildList {
        for (format in formats) {
            var stableCandidate: DirectUsbCalibrationCandidate? = null
            for (bufferFrame in frames) {
                for (periodMultiplier in multipliers) {
                    val candidate = DirectUsbCalibrationCandidate(bufferFrame, periodMultiplier)
                    if (!shouldAttemptDirectUsbCalibrationCandidate(candidate, stableCandidate)) break
                    add(format to candidate)
                    if (isStable(format, candidate)) stableCandidate = candidate
                }
            }
        }
    }
}

fun filterDirectUsbFormatsForSampleRate(
    formats: Iterable<DirectUsbFormat>,
    fixedSampleRate: Int?
): List<DirectUsbFormat> =
    fixedSampleRate?.let { rate -> formats.filter { it.sampleRate == rate } } ?: formats.toList()


data class DirectUsbCalibrationProgress(
    val profileIndex: Int,
    val profileCount: Int,
    val profileLabel: String,
    val status: String,
    val candidateFrames: Int = 0,
    val candidateIndex: Int = profileIndex,
    val candidateCount: Int = profileCount,
    val passed: Boolean? = null,
    val message: String = status
)

data class DirectUsbCalibrationResult(
    val profiles: List<DirectUsbCalibrationProfile>,
    val success: Boolean,
    val message: String,
    val vendorId: Int = 0,
    val productId: Int = 0,
    val format: DirectUsbFormat = profiles.firstOrNull()?.format
        ?: DirectUsbFormat(48_000, 32, 4),
    val selectedFrames: Int = profiles.firstOrNull { it.stable }?.latencyFrames?.toInt() ?: 0,
    val selectedMilliseconds: Double = profiles.firstOrNull { it.stable }?.latencyMilliseconds ?: 0.0,
    val passedCandidates: List<Int> = profiles.filter { it.stable }.map { it.latencyFrames.toInt() },
    val failedCandidates: List<Int> = profiles.filterNot { it.stable }.map { it.latencyFrames.toInt() }
)


/**
 * Owns the app-permitted USB connection used by the direct USB audio session.
 * Native code captures all negotiated input channels and sends the processed
 * stereo signal through libusb; Android AudioManager routing is not involved.
 */
object DirectUsbAudioManager {
    private const val TAG = "DirectUsbAudio"
    private const val ACTION_USB_PERMISSION =
        "com.vibes.dsp.action.DIRECT_USB_PERMISSION"
    private const val CALIBRATION_WARMUP_MS = 1_500L
    private const val CALIBRATION_MAX_CANDIDATES = 20
    private const val CALIBRATION_SAFETY_STEPS = 4
    private const val CALIBRATION_MEASURE_MS = 10_000L
    private const val CALIBRATION_CYCLES = 2

    private fun greatestCommonDivisor(left: Int, right: Int): Int {
        var a = left.coerceAtLeast(1)
        var b = right.coerceAtLeast(1)
        while (b != 0) {
            val remainder = a % b
            a = b
            b = remainder
        }
        return a
    }

    private fun calibrationStep(graphFrames: Int, transferFrames: Int): Int {
        val graph = graphFrames.coerceAtLeast(4)
        val transfer = transferFrames.coerceAtLeast(1)
        return greatestCommonDivisor(graph, transfer).coerceAtLeast(16)
    }
    private val supportedLine6ProductIds = setOf(0x4141, 0x4150, 0x5555)

    private fun isSupportedLine6(device: UsbDevice): Boolean =
        device.vendorId == 0x0e41 && device.productId in supportedLine6ProductIds

    private fun selectedDriver(context: Context) = AudioSettingsManager.getUsbAudioDriver(context)
    private val fallbackFormats = listOf(
        DirectUsbFormat(44_100, 16, 2),
        DirectUsbFormat(44_100, 24, 3),
        DirectUsbFormat(48_000, 16, 2),
        DirectUsbFormat(48_000, 24, 3),
        DirectUsbFormat(48_000, 24, 4, 4),
        DirectUsbFormat(48_000, 32, 4)
    )
    private var connection: UsbDeviceConnection? = null
    private var activeDeviceId: Int? = null
    private var detachReceiver: BroadcastReceiver? = null
    private var availableInputChannels = 0
    private val lifecycleMutex = Mutex()
    private val activeCalibrationJob = AtomicReference<Job?>(null)

    private fun resolveLine6DeviceSelection(
        driver: UsbAudioDriver,
        showAllUsbDevices: Boolean,
        devices: Collection<UsbDevice>
    ): List<UsbDevice> {
        val filteredDevices = devices.filter { device ->
            when {
                driver == UsbAudioDriver.Line6 && showAllUsbDevices -> true
                driver == UsbAudioDriver.Line6 -> isSupportedLine6(device)
                else -> isUsbAudioDevice(device)
            }
        }
        return if (driver == UsbAudioDriver.Line6) {
            if (showAllUsbDevices) filteredDevices else filteredDevices.ifEmpty {
                devices.filter { isSupportedLine6(it) || isUsbAudioDevice(it) }
            }
        } else {
            filteredDevices
        }
    }

    private fun formatDeviceLineForDiagnostics(device: UsbDevice): String {
        val interfaces = (0 until device.interfaceCount).joinToString(
            separator = ",",
            prefix = "[",
            postfix = "]"
        ) { index ->
            val usbInterface = device.getInterface(index)
            "${usbInterface.interfaceClass}/${usbInterface.interfaceSubclass}/${usbInterface.interfaceProtocol}"
        }
        return "${buildDeviceName(device)} [vid=0x${device.vendorId.toString(16)} " +
            "pid=0x${device.productId.toString(16)} name=${device.deviceName}] " +
            "class=${device.deviceClass} interfaces=$interfaces"
    }

    fun getAudioDevicesDebugLog(context: Context): String {
        return try {
            val usbManager = context.getSystemService(Context.USB_SERVICE) as UsbManager
            val driver = selectedDriver(context)
            val showAllUsbDevices = driver == UsbAudioDriver.Line6 &&
                AudioSettingsManager.getLine6ShowAllUsbDevices(context)
            val devices = usbManager.deviceList.values.toList()
                .sortedBy { it.deviceName }
            val filteredDevices = resolveLine6DeviceSelection(driver, showAllUsbDevices, devices)
            val selectedIds = filteredDevices.map { it.deviceId }.toHashSet()
            buildString {
                appendLine("USB device scan")
                appendLine("Driver=$driver, showAllUsbDevices=$showAllUsbDevices")
                appendLine("Total USB devices=${devices.size}, visible devices=${filteredDevices.size}")
                appendLine()
                appendLine("Visible devices:")
                if (filteredDevices.isEmpty()) {
                    appendLine("(none)")
                } else {
                    filteredDevices.forEach { device ->
                        appendLine("  [${device.deviceId}] ${formatDeviceLineForDiagnostics(device)}")
                    }
                }
                appendLine()
                appendLine("All devices:")
                devices.forEach { device ->
                    val include = if (selectedIds.contains(device.deviceId)) "yes" else "no"
                    val reason = when {
                        driver == UsbAudioDriver.Uac && isUsbAudioDevice(device) -> "usb-audio"
                        driver == UsbAudioDriver.Line6 && showAllUsbDevices -> "line6-show-all"
                        driver == UsbAudioDriver.Line6 && (isSupportedLine6(device) || isUsbAudioDevice(device)) -> "line6-fallback"
                        driver == UsbAudioDriver.Line6 && isSupportedLine6(device) -> "line6-vidpid"
                        driver == UsbAudioDriver.Line6 -> "line6-no-match"
                        else -> "other"
                    }
                    appendLine("  [$include] [${device.deviceId}] $reason ${formatDeviceLineForDiagnostics(device)}")
                }
            }
        } catch (error: Throwable) {
            "Failed to collect USB device diagnostic log: ${error.message}"
        }
    }

    fun getAudioDevices(context: Context): List<DirectUsbDeviceOption> {
        val usbManager = context.getSystemService(Context.USB_SERVICE) as UsbManager
        val driver = selectedDriver(context)
        val showAllUsbDevices = driver == UsbAudioDriver.Line6 &&
            AudioSettingsManager.getLine6ShowAllUsbDevices(context)
        return resolveLine6DeviceSelection(driver, showAllUsbDevices, usbManager.deviceList.values)
            .sortedBy { it.deviceName }
            .map { device ->
                DirectUsbDeviceOption(device.deviceId, buildDeviceName(device), device.vendorId, device.productId, device)
            }
    }



    suspend fun probeFormats(
        context: Context, option: DirectUsbDeviceOption
    ): Result<List<DirectUsbFormat>> = lifecycleMutex.withLock {
        probeFormatsInternal(context, option)
    }

    private suspend fun probeFormatsInternal(
        context: Context, option: DirectUsbDeviceOption
    ): Result<List<DirectUsbFormat>> =
        withContext(Dispatchers.IO) {
            val engine = NativeEngine.getInstance()
            val reusingOpenDevice = activeDeviceId == option.id && connection != null
            if (!reusingOpenDevice) {
                disableInternal(context)
                val usbManager = context.getSystemService(Context.USB_SERVICE) as UsbManager
                if (!requestPermission(context, usbManager, option.device)) {
                    return@withContext Result.failure(SecurityException("USB access was not granted"))
                }
                val opened = usbManager.openDevice(option.device)
                    ?: return@withContext Result.failure(
                        IllegalStateException("Android could not open the USB interface")
                    )
                if (opened.fileDescriptor < 0 || !engine.nativeOpenDirectUsbOutput(opened.fileDescriptor, selectedDriver(context).code)) {
                    opened.close()
                    return@withContext Result.failure(
                        IllegalStateException(
                            "Could not take control of USB audio. Enable Disable USB audio routing and reconnect the interface."
                        )
                    )
                }
                connection = opened
                activeDeviceId = option.id
                registerDetachReceiver(context.applicationContext)
            }
            availableInputChannels = engine.nativeGetDirectUsbInputChannelCount()
            if (availableInputChannels <= 0) {
                disableInternal(context)
                return@withContext Result.failure(
                    IllegalStateException("The USB interface exposes no PCM capture channels")
                )
            }
            val driver = selectedDriver(context)
            if (driver == UsbAudioDriver.Line6) {
                val formats = listOf(DirectUsbFormat(44_100, 16, 2, 2))
                AudioSettingsManager.setDirectUsbDeviceId(context, option.id)
                AudioSettingsManager.setDirectUsbIdentity(context, option.vendorId, option.productId, option.name)
                AudioSettingsManager.setDirectUsbCachedFormats(context, formats)
                return@withContext Result.success(formats)
            }
            val packedFormats = runCatching { engine.nativeGetDirectUsbOutputFormats() }
                .getOrNull() ?: intArrayOf()
            val nativeFormats = packedFormats
                .asSequence()
                .chunked(4)
                .filter { it.size == 4 && it[0] > 0 && it[1] > 0 && it[2] > 0 && it[3] > 0 }
                .map { DirectUsbFormat(it[0], it[1], it[2], it[3]) }
                .toList()
            val formats = nativeFormats
            AudioSettingsManager.setDirectUsbDeviceId(context, option.id)
            AudioSettingsManager.setDirectUsbIdentity(
                context, option.vendorId, option.productId, option.name
            )
            AudioSettingsManager.setDirectUsbCachedFormats(context, formats)
            Result.success(formats)
        }

    suspend fun startConfigured(context: Context): Result<Unit> =
        lifecycleMutex.withLock {
            if (AudioSettingsManager.getAudioBackend(context) == AudioBackend.AndroidOboe) {
                val ok = NativeEngine.getInstance().nativeStartAndroidOboeSession(
                    inputDeviceId = AudioSettingsManager.getAndroidInputDeviceId(context),
                    outputDeviceId = AudioSettingsManager.getAndroidOutputDeviceId(context),
                    bufferFrames = AudioSettingsManager.getBufferSize(context)
                )
                if (ok) {
                    availableInputChannels = 2
                    return@withLock Result.success(Unit)
                }
                availableInputChannels = 0
                return@withLock Result.failure(IllegalStateException("Android Oboe backend failed to start"))
            }
            val persistedDeviceId = AudioSettingsManager.getDirectUsbDeviceId(context)
            val vendorId = AudioSettingsManager.getDirectUsbVendorId(context)
            val productId = AudioSettingsManager.getDirectUsbProductId(context)
            val devices = getAudioDevices(context)
            val device = devices.firstOrNull { it.id == persistedDeviceId }
                ?: devices.firstOrNull { it.vendorId == vendorId && it.productId == productId }
                ?: return@withLock Result.failure(IllegalStateException("No configured USB audio device"))
            val selected = if (selectedDriver(context) == UsbAudioDriver.Line6) {
                DirectUsbFormat(44_100, 16, 2, 2)
            } else {
                DirectUsbFormat(
                    AudioSettingsManager.getDirectUsbRate(context),
                    AudioSettingsManager.getDirectUsbBits(context),
                    AudioSettingsManager.getDirectUsbSubslot(context),
                    AudioSettingsManager.getDirectUsbChannels(context)
                )
            }
            val available = probeFormatsInternal(context, device)
                .getOrElse { return@withLock Result.failure(it) }
            val exact = available.firstOrNull {
                it.sampleRate == selected.sampleRate && it.bits == selected.bits &&
                    it.subslotBytes == selected.subslotBytes &&
                    it.channels == selected.channels
            } ?: return@withLock Result.failure(
                IllegalStateException("Configured USB format is unavailable")
            )
            val outputPair = AudioSettingsManager.getDirectUsbOutputPair(context)
                .coerceIn(0, (exact.channels / 2 - 1).coerceAtLeast(0))
            AudioSettingsManager.setDirectUsbOutputPair(context, outputPair)
            val bufferConfig = AudioSettingsManager.getDirectUsbBufferConfig(context)
            startExact(context, exact, outputPair, bufferConfig)
        }

    private fun startExact(
        context: Context,
        exact: DirectUsbFormat,
        outputPair: Int,
        bufferConfig: DirectUsbBufferConfig,
        bufferFrames: Int = AudioSettingsManager.getBufferSize(context),
        periodMultiplier: Int =
            AudioSettingsManager.getDirectUsbPeriodMultiplier(context)
    ): Result<Unit> {
        val engine = NativeEngine.getInstance()
        if (!engine.nativeStartDirectUsbSession(
                exact.sampleRate, exact.bits, exact.subslotBytes, exact.channels,
                outputPair, bufferFrames, periodMultiplier,
                bufferConfig.playbackTargetFrames, bufferConfig.startupPrimeFrames,
                bufferConfig.writeHeadroomFrames, bufferConfig.captureLimitFrames,
                bufferConfig.transferCount, bufferConfig.packetsPerTransfer,
                bufferConfig.ringCapacityBytes,
                AudioSettingsManager.getDirectUsbThermalSafetyEnabled(context)
            )
        ) {
            val stats = runCatching { engine.getDirectUsbStats() }.getOrNull()
            val failure = stats?.failure ?: DirectUsbFailure.Unknown
            val detail = runCatching { engine.nativeGetDirectUsbErrorDetail() }
                .getOrNull()
                ?.trim()
                ?.takeIf { it.isNotEmpty() }
            val message = buildString {
                append("USB start failed [${failure.name}] for ${exact.label}")
                if (detail != null) append(": $detail")
                else append(". Check the interface format and USB audio routing settings.")
            }
            disableInternal(context)
            return Result.failure(IllegalStateException(message))
        }
        return Result.success(Unit)
    }

    private fun bufferConfigWithTarget(
        context: Context,
        playbackTargetFrames: Int
    ): DirectUsbBufferConfig = AudioSettingsManager.getDirectUsbBufferConfig(context)
        .copy(playbackTargetFrames = playbackTargetFrames)
    private suspend fun measureExactProfile(
        context: Context,
        option: DirectUsbDeviceOption,
        template: DirectUsbCalibrationProfile
    ): DirectUsbCalibrationProfile = lifecycleMutex.withLock {
        withContext(Dispatchers.IO) {
            val ranAt = System.currentTimeMillis()
            val pair = AudioSettingsManager.getDirectUsbOutputPair(context)
                .coerceIn(0, (template.format.channels / 2 - 1).coerceAtLeast(0))
            try {
                probeFormatsInternal(context, option).getOrThrow()
                startExact(
                    context, template.format, pair, template.bufferConfig,
                    template.bufferFrames, template.periodMultiplier
                ).getOrThrow()
                delay(CALIBRATION_WARMUP_MS)
                val measured = NativeEngine.getInstance().getDirectUsbStats()
                delay(CALIBRATION_MEASURE_MS)
                val after = NativeEngine.getInstance().getDirectUsbStats()
                val xruns = (after.actualXruns - measured.actualXruns).coerceAtLeast(0)
                val misses = (after.deadlineMisses - measured.deadlineMisses).coerceAtLeast(0)
                val errors = (after.captureTransferErrors - measured.captureTransferErrors +
                    after.playbackTransferErrors - measured.playbackTransferErrors).coerceAtLeast(0)
                val started = after.state == DirectUsbSessionState.Running
                val stable = started && after.failure == DirectUsbFailure.Ok && !after.transportFailed &&
                    xruns == 0L && misses == 0L && errors == 0L && after.queuedOut > 0 &&
                    after.lastCycleNs > 0 && after.deadlineBudgetNs > 0
                template.copy(
                    id = "${template.id}:remeasure:$ranAt",
                    ranAtEpochMs = ranAt,
                    started = started,
                    stable = stable,
                    failure = if (stable) null else "Safety checks failed",
                    latencyFrames = after.knownHostLatencyFrames,
                    latencyMilliseconds = after.knownHostLatencyFrames * 1000.0 / template.format.sampleRate,
                    xruns = xruns,
                    deadlineMisses = misses,
                    transferErrors = errors,
                    attemptedRuns = 1,
                    successfulRuns = if (started) 1 else 0
                )
            } catch (cancelled: kotlinx.coroutines.CancellationException) {
                throw cancelled
            } catch (error: Throwable) {
                template.copy(
                    id = "${template.id}:remeasure:$ranAt",
                    ranAtEpochMs = ranAt,
                    started = false,
                    stable = false,
                    failure = error.message ?: "Calibration failed",
                    latencyFrames = 0,
                    latencyMilliseconds = 0.0,
                    xruns = 0,
                    deadlineMisses = 0,
                    transferErrors = 0,
                    attemptedRuns = 1,
                    successfulRuns = 0
                )
            } finally {
                disableInternal(context)
            }
        }
    }

    suspend fun calibrate(
        context: Context,
        option: DirectUsbDeviceOption,
        format: DirectUsbFormat,
        includeExperimental: Boolean = false,
        dangerOverride: Boolean = false,
        fixedSampleRate: Int? = null,
        onProgress: (DirectUsbCalibrationProgress) -> Unit = {},
        stopAfterFirstStable: Boolean = true
    ): DirectUsbCalibrationResult {
        val calibrationJob = requireNotNull(coroutineContext[Job])
        check(activeCalibrationJob.compareAndSet(null, calibrationJob)) { "USB calibration is already running" }
        try {
            return lifecycleMutex.withLock {
                withContext(Dispatchers.IO) {
                    val config = AudioSettingsManager.getDirectUsbBufferConfig(context)
                    val profiles = mutableListOf<DirectUsbCalibrationProfile>()
                    fun diagnostic(candidate: DirectUsbFormat, message: String, minFrames: Int = 0) =
                        DirectUsbCalibrationProfile(
                            "${option.vendorId}:${option.productId}:${candidate.sampleRate}:${candidate.bits}:${candidate.subslotBytes}:${candidate.channels}:diagnostic:${System.currentTimeMillis()}",
                            candidate, 0, 1, config, false, System.currentTimeMillis(), false, false,
                            message, 0, 0.0, 0, 0, 0, minFrames, dangerOverride
                        )
                    val discovered = probeFormatsInternal(context, option)
                    val fallbackFormat = fixedSampleRate?.let { format.copy(sampleRate = it) } ?: format
                    val advertised: List<DirectUsbFormat>
                    if (discovered.isSuccess) {
                        val discoveredFormats = discovered.getOrThrow()
                        advertised = filterDirectUsbFormatsForSampleRate(discoveredFormats, fixedSampleRate)
                        if (fixedSampleRate != null && advertised.isEmpty()) {
                            val failure = diagnostic(
                                fallbackFormat,
                                "Device advertised no output format at fixed sample rate $fixedSampleRate Hz"
                            )
                            profiles += failure
                            AudioSettingsManager.persistDirectUsbCalibrationProfile(
                                context, option.vendorId, option.productId, failure
                            )
                            return@withContext DirectUsbCalibrationResult(
                                profiles, false, failure.failure ?: "No matching fixed sample rate",
                                option.vendorId, option.productId, fallbackFormat
                            )
                        }
                    } else {
                        val failure = diagnostic(fallbackFormat, "Capability probe failed: ${discovered.exceptionOrNull()?.message}")
                        profiles += failure
                        AudioSettingsManager.persistDirectUsbCalibrationProfile(context, option.vendorId, option.productId, failure)
                        if (!dangerOverride) {
                            return@withContext DirectUsbCalibrationResult(profiles, false, failure.failure ?: "Capability probe failed",
                                option.vendorId, option.productId, fallbackFormat)
                        }
                        advertised = emptyList()
                    }
                    val candidates = if (advertised.isNotEmpty()) advertised else if (dangerOverride) listOf(fallbackFormat) else emptyList()
                    if (advertised.isEmpty()) {
                        val failure = diagnostic(
                            fallbackFormat,
                            if (dangerOverride) "No advertised formats; using DANGER fallback"
                            else "Device advertised no output formats"
                        )
                        profiles += failure
                        AudioSettingsManager.persistDirectUsbCalibrationProfile(context, option.vendorId, option.productId, failure)
                    }
                    val automatic = config.copy(
                        playbackTargetFrames = 0, startupPrimeFrames = 0, writeHeadroomFrames = 0,
                        captureLimitFrames = 0, transferCount = 0, packetsPerTransfer = 0, ringCapacityBytes = 0
                    )
                    val minimums = mutableMapOf<DirectUsbFormat, Int>()
                    for (candidate in candidates) {
                        if (advertised.isNotEmpty()) {
                            var failure: String? = null
                            var minimum = 0
                            try {
                                disableInternal(context)
                                probeFormatsInternal(context, option).getOrThrow()
                                val pair = AudioSettingsManager.getDirectUsbOutputPair(context)
                                    .coerceIn(0, (candidate.channels / 2 - 1).coerceAtLeast(0))
                                startExact(context, candidate, pair, automatic, 1024, 1).getOrThrow()
                                delay(CALIBRATION_WARMUP_MS)
                                val stats = NativeEngine.getInstance().getDirectUsbStats()
                                if (stats.state != DirectUsbSessionState.Running) {
                                    failure = "Capability probe did not reach Running (${stats.failure.name})"
                                } else {
                                    minimum = stats.captureTransferFrames.toInt().coerceAtLeast(4)
                                }
                            } catch (error: Throwable) {
                                failure = "Capability probe failed: ${error.message}"
                            } finally {
                                disableInternal(context)
                            }
                            if (failure != null) {
                                val failed = diagnostic(candidate, failure, minimum)
                                profiles += failed
                                AudioSettingsManager.persistDirectUsbCalibrationProfile(context, option.vendorId, option.productId, failed)
                                continue
                            }
                            minimums[candidate] = minimum
                        } else {
                            minimums[candidate] = 0
                        }
                    }
                    val standard = setOf(16, 32, 64, 128, 256, 512)
                    val experimental = setOf(4, 6, 8, 12, 24, 48, 72, 96)
                    val requestedFrames = (standard + if (includeExperimental) experimental else emptySet()).toList().sorted()
                    val calibrationMultipliers = 1..4
                    val total = minimums.values.sumOf { min ->
                        requestedFrames.count { dangerOverride || it >= min } *
                            calibrationMultipliers.count()
                    }
                    var index = 0
                    for ((candidateFormat, minFrames) in minimums) {
                        val frames = requestedFrames.filter { dangerOverride || it >= minFrames }
                        var stableCandidate: DirectUsbCalibrationCandidate? = null
                        candidateFrames@ for (bufferFrames in frames) {
                            for (multiplier in calibrationMultipliers) {
                                val candidate = DirectUsbCalibrationCandidate(bufferFrames, multiplier)
                                if (!shouldAttemptDirectUsbCalibrationCandidate(
                                        candidate, stableCandidate, stopAfterFirstStable
                                    )
                                ) {
                                    break@candidateFrames
                                }
                            val label = "${candidateFormat.label} · ${bufferFrames} frames · ×$multiplier"
                            withContext(Dispatchers.Main) { onProgress(DirectUsbCalibrationProgress(index, total, label, "Starting")) }
                            val ranAt = System.currentTimeMillis()
                            val profile = try {
                                val pair = AudioSettingsManager.getDirectUsbOutputPair(context)
                                    .coerceIn(0, (candidateFormat.channels / 2 - 1).coerceAtLeast(0))
                                probeFormatsInternal(context, option).getOrThrow()
                                startExact(context, candidateFormat, pair, automatic, bufferFrames, multiplier).getOrThrow()
                                delay(CALIBRATION_WARMUP_MS)
                                val before = NativeEngine.getInstance().getDirectUsbStats()
                                val resolved = automatic.copy(playbackTargetFrames = before.steadyTarget.toInt().coerceAtLeast(0))
                                disableInternal(context)
                                probeFormatsInternal(context, option).getOrThrow()
                                startExact(context, candidateFormat, pair, resolved, bufferFrames, multiplier).getOrThrow()
                                delay(CALIBRATION_WARMUP_MS)
                                val measured = NativeEngine.getInstance().getDirectUsbStats()
                                delay(CALIBRATION_MEASURE_MS)
                                val after = NativeEngine.getInstance().getDirectUsbStats()
                                val xruns = (after.actualXruns - measured.actualXruns).coerceAtLeast(0)
                                val misses = (after.deadlineMisses - measured.deadlineMisses).coerceAtLeast(0)
                                val errors = (after.captureTransferErrors - measured.captureTransferErrors +
                                    after.playbackTransferErrors - measured.playbackTransferErrors).coerceAtLeast(0)
                                val started = after.state == DirectUsbSessionState.Running
                                val stable = started && after.failure == DirectUsbFailure.Ok && !after.transportFailed &&
                                    xruns == 0L && misses == 0L && errors == 0L && after.queuedOut > 0 &&
                                    after.lastCycleNs > 0 && after.deadlineBudgetNs > 0
                                DirectUsbCalibrationProfile(
                                    "${option.vendorId}:${option.productId}:${candidateFormat.sampleRate}:${candidateFormat.bits}:${candidateFormat.subslotBytes}:${candidateFormat.channels}:$bufferFrames:$multiplier",
                                    candidateFormat, bufferFrames, multiplier, resolved, bufferFrames !in standard, ranAt,
                                    started, stable, if (stable) null else "Safety checks failed",
                                    after.knownHostLatencyFrames, after.knownHostLatencyFrames * 1000.0 / candidateFormat.sampleRate,
                                    xruns, misses, errors, minFrames, dangerOverride
                                )
                            } catch (cancelled: kotlinx.coroutines.CancellationException) {
                                throw cancelled
                            } catch (error: Throwable) {
                                DirectUsbCalibrationProfile(
                                    "${option.vendorId}:${option.productId}:${candidateFormat.sampleRate}:${candidateFormat.bits}:${candidateFormat.subslotBytes}:${candidateFormat.channels}:$bufferFrames:$multiplier",
                                    candidateFormat, bufferFrames, multiplier, config, bufferFrames !in standard, ranAt,
                                    false, false, error.message ?: "Calibration failed", 0, 0.0, 0, 0, 0, minFrames, dangerOverride
                                )
                            } finally { disableInternal(context) }
                            profiles += profile
                            index++
                            withContext(Dispatchers.Main) {
                                onProgress(DirectUsbCalibrationProgress(index, total, label, if (profile.stable) "Stable" else "Failed",
                                    profile.latencyFrames.toInt(), index - 1, total, profile.stable, profile.failure ?: "Failed"))
                            }
                            AudioSettingsManager.persistDirectUsbCalibrationProfile(context, option.vendorId, option.productId, profile)
                            if (profile.stable) stableCandidate = candidate
                        }
                    }
                    }
                    DirectUsbCalibrationResult(profiles, profiles.any { it.stable },
                        if (profiles.any { it.stable }) "Calibration complete" else "No stable profiles",
                        option.vendorId, option.productId, candidates.firstOrNull() ?: format)
                }
            }
        } finally {
            activeCalibrationJob.compareAndSet(calibrationJob, null)
            disableInternal(context)
        }
    }
    suspend fun switchDriver(context: Context, driver: UsbAudioDriver) {
        if (driver == selectedDriver(context)) return
        // Calibration owns lifecycleMutex for its whole run. Cancel and join first so
        // its finally cleanup cannot race with the mode change or repopulate old prefs.
        activeCalibrationJob.get()?.let { calibration ->
            calibration.cancel(kotlinx.coroutines.CancellationException("USB driver changed"))
            calibration.join()
        }
        lifecycleMutex.withLock {
            disableInternal(context)
            AudioSettingsManager.clearDirectUsbSelection(context)
            AudioSettingsManager.setUsbAudioDriver(context, driver)
        }
    }
    suspend fun calibrateExtended(
        context: Context,
        option: DirectUsbDeviceOption,
        baseProfile: DirectUsbCalibrationProfile,
        onProgress: (DirectUsbCalibrationProgress) -> Unit = {}
    ): DirectUsbCalibrationResult {
        require(baseProfile.stable && !baseProfile.extended) {
            "Extended calibration requires a stable base profile"
        }
        val calibrationJob = requireNotNull(coroutineContext[Job])
        check(activeCalibrationJob.compareAndSet(null, calibrationJob)) { "USB calibration is already running" }
        try {
            return lifecycleMutex.withLock {
                withContext(Dispatchers.IO) {
                    val values = listOf(
                        "startup prime" to listOf(0, 16, 32, 48, 64, 96, 128, 144, 192, 256, 384, 512, 768, 1024, 1536, 2048, 3072, 4096),
                        "write headroom" to listOf(0, 16, 32, 48, 64, 96, 128, 144, 192, 256, 384, 512, 768, 1024, 1536, 2048, 3072, 4096),
                        "capture limit" to listOf(0, 16, 32, 48, 64, 96, 128, 144, 192, 256, 384, 512, 768, 1024, 1536, 2048, 3072, 4096),
                        "ring capacity" to listOf(0, 4, 8, 16, 32, 64, 128, 256, 512, 1024)
                    )
                    val candidates = values.flatMap { (name, entries) -> entries.map { name to it } }
                    val runId = System.nanoTime()
                    check(candidates.size == 64)
                    val profiles = mutableListOf<DirectUsbCalibrationProfile>()
                    val pair = AudioSettingsManager.getDirectUsbOutputPair(context)
                        .coerceIn(0, (baseProfile.format.channels / 2 - 1).coerceAtLeast(0))
                    candidates.forEachIndexed { index, (name, value) ->
                        coroutineContext.ensureActive()
                        val label = "Extended · $name = $value ${if (name == "ring capacity") "KiB" else "frames"}"
                        withContext(Dispatchers.Main) {
                            onProgress(DirectUsbCalibrationProgress(index, candidates.size, label, "Starting"))
                        }
                        val ranAt = System.currentTimeMillis()
                        val config = when (name) {
                            "startup prime" -> baseProfile.bufferConfig.copy(startupPrimeFrames = value)
                            "write headroom" -> baseProfile.bufferConfig.copy(writeHeadroomFrames = value)
                            "capture limit" -> baseProfile.bufferConfig.copy(captureLimitFrames = value)
                            else -> baseProfile.bufferConfig.copy(ringCapacityBytes = value * 1024)
                        }
                        val id = "${option.vendorId}:${option.productId}:extended:$runId:$index"
                        val profile = try {
                            probeFormatsInternal(context, option).getOrThrow()
                            startExact(context, baseProfile.format, pair, config,
                                baseProfile.bufferFrames, baseProfile.periodMultiplier).getOrThrow()
                            delay(CALIBRATION_WARMUP_MS)
                            val measured = NativeEngine.getInstance().getDirectUsbStats()
                            delay(CALIBRATION_MEASURE_MS)
                            val after = NativeEngine.getInstance().getDirectUsbStats()
                            val xruns = (after.actualXruns - measured.actualXruns).coerceAtLeast(0)
                            val misses = (after.deadlineMisses - measured.deadlineMisses).coerceAtLeast(0)
                            val errors = (after.captureTransferErrors - measured.captureTransferErrors +
                                after.playbackTransferErrors - measured.playbackTransferErrors).coerceAtLeast(0)
                            val started = after.state == DirectUsbSessionState.Running
                            val stable = started && after.failure == DirectUsbFailure.Ok && !after.transportFailed &&
                                xruns == 0L && misses == 0L && errors == 0L && after.queuedOut > 0 &&
                                after.lastCycleNs > 0 && after.deadlineBudgetNs > 0
                            DirectUsbCalibrationProfile(
                                id, baseProfile.format, baseProfile.bufferFrames, baseProfile.periodMultiplier,
                                config, true, ranAt, started, stable, if (stable) null else "Safety checks failed",
                                after.knownHostLatencyFrames,

                                after.knownHostLatencyFrames * 1000.0 / baseProfile.format.sampleRate,
                                xruns, misses, errors, baseProfile.deviceMinimumFrames, baseProfile.dangerous,
                                true, label
                            )
                        } catch (cancelled: kotlinx.coroutines.CancellationException) {
                            throw cancelled
                        } catch (error: Throwable) {
                            DirectUsbCalibrationProfile(
                                id, baseProfile.format, baseProfile.bufferFrames, baseProfile.periodMultiplier,
                                config, true, ranAt, false, false, error.message ?: "Calibration failed",
                                0, 0.0, 0, 0, 0, baseProfile.deviceMinimumFrames, baseProfile.dangerous,
                                true, label
                            )
                        } finally {
                            disableInternal(context)
                        }
                        profiles += profile
                        withContext(Dispatchers.Main) {
                            onProgress(DirectUsbCalibrationProgress(index + 1, candidates.size, label,
                                if (profile.stable) "Stable" else "Failed",
                                profile.latencyFrames.toInt(), index, candidates.size, profile.stable,
                                profile.failure ?: "Failed"))
                        }
                        AudioSettingsManager.persistDirectUsbCalibrationProfile(
                            context, option.vendorId, option.productId, profile
                        )
                    }
                    DirectUsbCalibrationResult(profiles, profiles.any { it.stable },
                        if (profiles.any { it.stable }) "Extended calibration complete" else "No stable extended profiles",
                        option.vendorId, option.productId, baseProfile.format)
                }
            }
        } finally {
            activeCalibrationJob.compareAndSet(calibrationJob, null)
            disableInternal(context)
        }
    }


    suspend fun autoCalibrate(
        context: Context, option: DirectUsbDeviceOption, includeExperimental: Boolean = false,
        dangerOverride: Boolean = false,
        fixedSampleRate: Int? = null,
        onProgress: (DirectUsbCalibrationProgress) -> Unit = {}
    ): DirectUsbAutoCalibrationResult {
        val format = AudioSettingsManager.getDirectUsbCachedFormats(context).firstOrNull()
            ?: DirectUsbFormat(48_000, 32, 4)
        val initialPrimary = calibrate(
            context, option, format, includeExperimental, dangerOverride, fixedSampleRate,
            onProgress = { p ->
                onProgress(p.copy(profileCount = p.profileCount * 5, candidateCount = p.candidateCount * 5))
            },
            stopAfterFirstStable = false
        )
        val primaryProfiles = initialPrimary.profiles.toMutableList()
        val initialPrimaryProfiles = initialPrimary.profiles
        initialPrimaryProfiles.forEachIndexed { index, initial ->
            if (!initial.started) return@forEachIndexed
            repeat(4) { retry ->
                coroutineContext.ensureActive()
                val measured = measureExactProfile(context, option, initial)
                primaryProfiles += measured
                onProgress(
                    DirectUsbCalibrationProgress(
                        profileIndex = initialPrimaryProfiles.size + index * 4 + retry,
                        profileCount = initialPrimaryProfiles.size * 5,
                        profileLabel = "Auto · ${initial.label}",
                        status = if (measured.stable) "Stable" else "Failed",
                        candidateFrames = measured.latencyFrames.toInt(),
                        candidateIndex = initialPrimaryProfiles.size + index * 4 + retry,
                        candidateCount = initialPrimaryProfiles.size * 5,
                        passed = measured.stable,
                        message = measured.failure ?: "Measured"
                    )
                )
            }
        }
        data class AutoMeasurementKey(
            val format: DirectUsbFormat,
            val bufferFrames: Int,
            val periodMultiplier: Int,
            val bufferConfig: DirectUsbBufferConfig,
            val label: String
        )
        fun aggregate(runs: List<DirectUsbCalibrationResult>, extended: Boolean): List<DirectUsbCalibrationProfile> =
            runs.flatMap { it.profiles }.filter { it.bufferFrames > 0 && it.failure?.startsWith("Capability probe") != true }
                .groupBy { AutoMeasurementKey(it.format, it.bufferFrames, it.periodMultiplier, it.bufferConfig, it.label) }.map { (_, values) ->
                    val measured = values.filter { it.started }
                    values.last().copy(id = "${values.last().id}:auto:${if (extended) "extended" else "primary"}",
                        label = "Auto · ${values.last().label}", autoGenerated = true,
                        attemptedRuns = values.size, successfulRuns = measured.size,
                        stable = values.size == (if (extended) 2 else 5) &&
                            values.all { it.started && it.stable },
                        latencyFrames = measured.map { it.latencyFrames }.average().takeIf { !it.isNaN() }?.toLong() ?: 0,
                        latencyMilliseconds = measured.map { it.latencyMilliseconds }.average().takeIf { !it.isNaN() } ?: 0.0,
                        xruns = values.sumOf { it.xruns }, deadlineMisses = values.sumOf { it.deadlineMisses },
                        transferErrors = values.sumOf { it.transferErrors }, extended = extended)
                }
        val primary = scoreAutoCalibrationProfileList(
            aggregate(listOf(initialPrimary.copy(profiles = primaryProfiles)), false)
        )
        primary.forEach { AudioSettingsManager.persistDirectUsbCalibrationProfile(context, option.vendorId, option.productId, it) }
        val selectedPrimary = scoreAutoCalibrationProfiles(primary)
            ?: return DirectUsbAutoCalibrationResult(primary, emptyList(), null, null, null, false, "No stable primary profiles")
        val initialExtended = calibrateExtended(context, option, selectedPrimary) { p ->
            onProgress(p.copy(profileIndex = primaryProfiles.size + p.profileIndex,
                profileCount = primaryProfiles.size + p.profileCount * 2))
        }
        val extendedProfiles = initialExtended.profiles.toMutableList()
        val initialExtendedProfiles = initialExtended.profiles
        initialExtendedProfiles.forEachIndexed { index, initial ->
            if (!initial.started) return@forEachIndexed
            val measured = measureExactProfile(context, option, initial)
            extendedProfiles += measured
            onProgress(
                DirectUsbCalibrationProgress(
                    profileIndex = primaryProfiles.size + initialExtendedProfiles.size + index,
                    profileCount = primaryProfiles.size + initialExtendedProfiles.size * 2,
                    profileLabel = "Auto · ${initial.label}",
                    status = if (measured.stable) "Stable" else "Failed",
                    candidateFrames = measured.latencyFrames.toInt(),
                    candidateIndex = primaryProfiles.size + initialExtendedProfiles.size + index,
                    candidateCount = primaryProfiles.size + initialExtendedProfiles.size * 2,
                    passed = measured.stable,
                    message = measured.failure ?: "Measured"
                )
            )
        }
        val extended = scoreAutoCalibrationProfileList(
            aggregate(listOf(initialExtended.copy(profiles = extendedProfiles)), true)
        )
        extended.forEach { AudioSettingsManager.persistDirectUsbCalibrationProfile(context, option.vendorId, option.productId, it) }
        val selectedExtended = scoreAutoCalibrationProfiles(extended)
        return DirectUsbAutoCalibrationResult(primary, extended, selectedPrimary, selectedExtended,
            selectedExtended ?: selectedPrimary, true, "Auto calibration complete")
    }
    fun startSelected(context: Context, format: DirectUsbFormat): Result<Unit> {
        AudioSettingsManager.setDirectUsbFormat(
            context, format.sampleRate, format.bits, format.subslotBytes, format.channels
        )
        return Result.success(Unit)
    }

    fun disable(context: Context) {
        val calibration = activeCalibrationJob.get()
        if (calibration != null) {
            calibration.cancel(
                kotlinx.coroutines.CancellationException("USB audio stopped")
            )
            return
        }
        disableInternal(context)
    }

    private fun disableInternal(context: Context) {
        val engine = NativeEngine.getInstance()
        if (AudioSettingsManager.getAudioBackend(context) == AudioBackend.AndroidOboe) {
            engine.stopEngine()
        } else {
            engine.nativeStopDirectUsbOutput()
            engine.nativeCloseDirectUsbOutput()
        }
        runCatching { engine.nativeFlushPgoProfile() }
        connection?.close()
        connection = null
        activeDeviceId = null
        availableInputChannels = 0
        unregisterDetachReceiver(context.applicationContext)
    }


    fun isStreaming(): Boolean = NativeEngine.getInstance().nativeIsDirectUsbOutputStreaming()

    fun getInputChannelCount(): Int = availableInputChannels

    private fun isUsbAudioDevice(device: UsbDevice): Boolean =
        device.deviceClass == UsbConstants.USB_CLASS_AUDIO ||
            (0 until device.interfaceCount).any { index ->
                device.getInterface(index).interfaceClass == UsbConstants.USB_CLASS_AUDIO
            }

    private fun buildDeviceName(device: UsbDevice): String {
        val manufacturer = device.manufacturerName?.takeIf(String::isNotBlank)
        val product = device.productName?.takeIf(String::isNotBlank)
        return listOfNotNull(manufacturer, product).joinToString(" ").ifBlank {
            "USB audio device ${device.vendorId.toString(16)}:${device.productId.toString(16)}"
        }
    }

    private suspend fun requestPermission(
        context: Context,
        usbManager: UsbManager,
        device: UsbDevice
    ): Boolean {
        if (usbManager.hasPermission(device)) return true
        return suspendCancellableCoroutine { continuation ->
            val receiver = object : BroadcastReceiver() {
                override fun onReceive(receiverContext: Context, intent: Intent) {
                    if (intent.action != ACTION_USB_PERMISSION) return
                    runCatching { context.unregisterReceiver(this) }
                    val granted = intent.getBooleanExtra(
                        UsbManager.EXTRA_PERMISSION_GRANTED, false
                    )
                    if (continuation.isActive) continuation.resume(granted)
                }
            }
            val filter = IntentFilter(ACTION_USB_PERMISSION)
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                context.registerReceiver(receiver, filter, Context.RECEIVER_NOT_EXPORTED)
            } else {
                @Suppress("UnspecifiedRegisterReceiverFlag")
                context.registerReceiver(receiver, filter)
            }
            continuation.invokeOnCancellation { runCatching { context.unregisterReceiver(receiver) } }
            val flags = PendingIntent.FLAG_UPDATE_CURRENT or
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) PendingIntent.FLAG_MUTABLE else 0
            val intent = Intent(ACTION_USB_PERMISSION).setPackage(context.packageName)
            usbManager.requestPermission(device, PendingIntent.getBroadcast(context, 0, intent, flags))
        }
    }

    private fun registerDetachReceiver(context: Context) {
        val receiver = object : BroadcastReceiver() {
            override fun onReceive(receiverContext: Context, intent: Intent) {
                if (intent.action != UsbManager.ACTION_USB_DEVICE_DETACHED) return
                val device = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
                    intent.getParcelableExtra(UsbManager.EXTRA_DEVICE, UsbDevice::class.java)
                } else {
                    @Suppress("DEPRECATION")
                    intent.getParcelableExtra(UsbManager.EXTRA_DEVICE)
                }
                if (device?.deviceId == activeDeviceId) {
                    Log.i(TAG, "Direct USB device detached")
                    disable(context)
                }
            }
        }
        val filter = IntentFilter(UsbManager.ACTION_USB_DEVICE_DETACHED)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
            context.registerReceiver(receiver, filter, Context.RECEIVER_NOT_EXPORTED)
        } else {
            @Suppress("UnspecifiedRegisterReceiverFlag")
            context.registerReceiver(receiver, filter)
        }
        detachReceiver = receiver
    }

    private fun unregisterDetachReceiver(context: Context) {
        detachReceiver?.let { receiver -> runCatching { context.unregisterReceiver(receiver) } }
        detachReceiver = null
    }
}
