schema = 1
id = "jsfx.geraint-luff"
name = "Geraint Luff JSFX"
version = "e98d6440"
format = "jsfx"
arch = ["arm64-v8a"]
manufacturer = "Geraint Luff"
tags = ["effects", "dynamics", "delay", "modulation", "utility"]
description = "Geraint Luff's collection of experimental audio effects and utility processors for REAPER."
license = "custom"

[payload]
kind = "archive"
url = "https://codeload.github.com/geraintluff/jsfx/zip/e98d64401ba57590b7ea0d3592675accb43667da"
sha256 = "5029a76f9d5b92b016abef72ce01545e410a2d328f73de89d791dcbf1e8b4181"
size = 43139322

[install]
entry = "jsfx-e98d64401ba57590b7ea0d3592675accb43667da/Bad Connection.jsfx"
