#include "RackGraph.h"

#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstring>

namespace guitarrackcraft {
namespace {
constexpr uint32_t kChannels = 2;
void silence(float* const* out, uint32_t frames) noexcept { if (!out) return; for (uint32_t c=0;c<kChannels;++c) if (out[c]) std::memset(out[c], 0, frames*sizeof(float)); }
void copyScaled(float* l,float* r,const float* inL,const float* inR,uint32_t n,float gain) noexcept { for(uint32_t i=0;i<n;++i){l[i]=inL[i]*gain;r[i]=inR[i]*gain;} }
void mixScaled(float* l,float* r,const float* inL,const float* inR,uint32_t n,float gain) noexcept { for(uint32_t i=0;i<n;++i){l[i]+=inL[i]*gain;r[i]+=inR[i]*gain;} }
}

RackGraph::RackGraph() : master_(std::make_shared<PluginChain>()) {
    auto first=std::make_shared<TrackNode>(); first->id=nextTrackId_++; first->chain=std::make_shared<PluginChain>(); tracks_.push_back(first); clips_.push_back(nullptr);
    activeOwner_=buildSnapshotLocked(tracks_, clips_); activeSnapshot_.store(activeOwner_.get(),std::memory_order_release); reclaimerThread_=std::thread(&RackGraph::reclaimerLoop,this);
}
RackGraph::~RackGraph(){ hazardSnapshot_.store(nullptr,std::memory_order_seq_cst); {std::lock_guard lock(reclaimerMutex_);reclaimerStop_=true;} reclaimerWake_.notify_one(); if(reclaimerThread_.joinable()) reclaimerThread_.join(); reclaimRetired(); }
double RackGraph::clipDuration(const WavClip& clip){return clip.sampleRate && !clip.left.empty()?static_cast<double>(clip.left.size())/clip.sampleRate:0.;}
std::unique_ptr<RackGraph::GraphSnapshot> RackGraph::buildSnapshotLocked(const std::vector<std::shared_ptr<TrackNode>>& nodes,const std::vector<std::shared_ptr<const WavClip>>& clips) const {
    if(nodes.size()!=clips.size()) return nullptr; auto snapshot=std::make_unique<GraphSnapshot>(); snapshot->master=master_; snapshot->capacity=bufferSize_; snapshot->mixLeft.resize(bufferSize_); snapshot->mixRight.resize(bufferSize_); snapshot->tracks.reserve(nodes.size());
    for(size_t i=0;i<nodes.size();++i){ if(!nodes[i]||!nodes[i]->chain||nodes[i]->sourceLeft.size()<bufferSize_||nodes[i]->sourceRight.size()<bufferSize_||nodes[i]->outputLeft.size()<bufferSize_||nodes[i]->outputRight.size()<bufferSize_) return nullptr; snapshot->tracks.push_back({nodes[i],clips[i]}); }
    return snapshot;
}
bool RackGraph::publishSnapshotLocked(std::unique_ptr<GraphSnapshot> next){ if(!next)return false; std::unique_ptr<RetiredSnapshot> retired; if(activeOwner_){retired=std::make_unique<RetiredSnapshot>();retired->owner=std::move(activeOwner_);} auto* raw=next.get(); activeOwner_=std::move(next); activeSnapshot_.exchange(raw,std::memory_order_release); if(retired){std::lock_guard lock(reclaimerMutex_);retired->next=retired_;retired_=retired.release();reclaimerWake_.notify_one();} return true; }
RackPathId RackGraph::addTrack(){std::lock_guard lock(controlMutex_);try{auto node=std::make_shared<TrackNode>();node->id=nextTrackId_;node->chain=std::make_shared<PluginChain>();node->sourceLeft.resize(bufferSize_);node->sourceRight.resize(bufferSize_);node->outputLeft.resize(bufferSize_);node->outputRight.resize(bufferSize_);if(sampleRate_.load()>0)node->chain->setSampleRate(sampleRate_.load(),bufferSize_);auto nodes=tracks_;auto clips=clips_;nodes.push_back(node);clips.push_back(nullptr);if(!publishSnapshotLocked(buildSnapshotLocked(nodes,clips)))return 0;tracks_=std::move(nodes);clips_=std::move(clips);return nextTrackId_++;}catch(...){return 0;}}
bool RackGraph::removeTrack(RackPathId id){std::lock_guard lock(controlMutex_);if(id==kMasterPathId||tracks_.size()<=1)return false;auto it=std::find_if(tracks_.begin(),tracks_.end(),[&](auto& n){return n->id==id;});if(it==tracks_.end())return false;auto nodes=tracks_;auto clips=clips_;auto i=static_cast<size_t>(it-tracks_.begin());nodes.erase(nodes.begin()+i);clips.erase(clips.begin()+i);if(!publishSnapshotLocked(buildSnapshotLocked(nodes,clips)))return false;tracks_=std::move(nodes);clips_=std::move(clips);return true;}
std::vector<TrackSnapshot> RackGraph::getTracks() const {std::lock_guard lock(controlMutex_);std::vector<TrackSnapshot> result;result.reserve(tracks_.size());auto rate=sampleRate_.load();if(rate<=0)rate=48000;for(size_t i=0;i<tracks_.size();++i){auto& n=*tracks_[i];auto& c=clips_[i];auto frame=n.statusFrame.load();result.push_back({n.id,n.volume.load(),n.inputArmed.load(),static_cast<bool>(c),c?c->displayName:std::string(),c?clipDuration(*c):0.,n.statusPlaying.load(),n.statusLooping.load(),static_cast<double>(frame)/rate,frame});}return result;}
bool RackGraph::setTrackVolume(RackPathId id,float value){std::lock_guard lock(controlMutex_);auto it=std::find_if(tracks_.begin(),tracks_.end(),[&](auto& n){return n->id==id;});if(it==tracks_.end())return false;(*it)->volume.store(std::clamp(value,0.f,1.f));return true;}
bool RackGraph::setTrackInputArmed(RackPathId id,bool armed){std::lock_guard lock(controlMutex_);auto it=std::find_if(tracks_.begin(),tracks_.end(),[&](auto& n){return n->id==id;});if(it==tracks_.end())return false;(*it)->inputArmed.store(armed);return true;}
bool RackGraph::attachTrackWav(RackPathId id,std::shared_ptr<const WavClip> clip){if(!clip||clip->left.empty()||!clip->sampleRate||(!clip->right.empty()&&clip->right.size()!=clip->left.size()))return false;std::lock_guard lock(controlMutex_);auto it=std::find_if(tracks_.begin(),tracks_.end(),[&](auto& n){return n->id==id;});if(it==tracks_.end())return false;auto copy=clips_;copy[it-tracks_.begin()]=std::move(clip);if(!publishSnapshotLocked(buildSnapshotLocked(tracks_,copy)))return false;clips_=std::move(copy);return true;}
bool RackGraph::unloadTrackWav(RackPathId id){std::lock_guard lock(controlMutex_);auto it=std::find_if(tracks_.begin(),tracks_.end(),[&](auto& n){return n->id==id;});if(it==tracks_.end())return false;auto copy=clips_;copy[it-tracks_.begin()].reset();if(!publishSnapshotLocked(buildSnapshotLocked(tracks_,copy)))return false;clips_=std::move(copy);return true;}
bool RackGraph::clearTrackWavs(){std::lock_guard lock(controlMutex_);auto copy=clips_;for(auto& c:copy)c.reset();if(!publishSnapshotLocked(buildSnapshotLocked(tracks_,copy)))return false;clips_=std::move(copy);return true;}
void RackGraph::writeMailboxLocked(bool changePlay,bool playing,bool reset,bool changeBpm,double bpm){mailbox_.sequence.fetch_add(1);if(changePlay){mailbox_.desiredPlaying.store(playing);mailbox_.playSerial.fetch_add(1);}if(changeBpm){mailbox_.desiredBpm.store(std::clamp(std::isfinite(bpm)?bpm:120.,20.,400.));mailbox_.bpmSerial.fetch_add(1);}if(reset)mailbox_.resetSerial.fetch_add(1);mailbox_.sequence.fetch_add(1,std::memory_order_release);}
bool RackGraph::setTransportPlaying(bool playing){std::lock_guard lock(controlMutex_);writeMailboxLocked(true,playing,false);return true;}bool RackGraph::restartTransport(){std::lock_guard lock(controlMutex_);writeMailboxLocked(true,true,true);return true;}void RackGraph::setBeatsPerMinute(double bpm){std::lock_guard lock(controlMutex_);writeMailboxLocked(false,false,false,true,bpm);}
bool RackGraph::setTrackTransportPlaying(RackPathId id,bool playing,LaunchQuantization quantization){std::lock_guard lock(controlMutex_);auto it=std::find_if(tracks_.begin(),tracks_.end(),[&](auto& n){return n->id==id;});if(it==tracks_.end())return false;auto& n=**it;n.desiredQuantization.store(static_cast<uint8_t>(quantization));n.desiredPlaying.store(playing);n.commandSerial.fetch_add(1,std::memory_order_release);return true;}
bool RackGraph::setTrackTransportLooping(RackPathId id,bool looping){std::lock_guard lock(controlMutex_);auto it=std::find_if(tracks_.begin(),tracks_.end(),[&](auto& n){return n->id==id;});if(it==tracks_.end())return false;(*it)->desiredLooping.store(looping);return true;}
TransportSnapshot RackGraph::getTransportSnapshot() const {TransportSnapshot r{};for(;;){auto before=statusSequence_.load(std::memory_order_acquire);if(before&1)continue;r={statusPlaying_.load(),statusPositionSec_.load(),statusBpm_.load(),statusSamplePosition_.load(),statusTransportFrame_.load()};if(before==statusSequence_.load(std::memory_order_acquire))return r;}}
std::shared_ptr<PluginChain> RackGraph::getChain(RackPathId id) const{std::lock_guard lock(controlMutex_);if(id==kMasterPathId)return master_;auto it=std::find_if(tracks_.begin(),tracks_.end(),[&](auto& n){return n->id==id;});return it==tracks_.end()?nullptr:(*it)->chain;}
void RackGraph::setSampleRate(float rate,uint32_t buffer){std::lock_guard lock(controlMutex_);sampleRate_.store(rate);bufferSize_=buffer;for(auto& n:tracks_){n->sourceLeft.resize(buffer);n->sourceRight.resize(buffer);n->outputLeft.resize(buffer);n->outputRight.resize(buffer);n->chain->setSampleRate(rate,buffer);}master_->setSampleRate(rate,buffer);(void)publishSnapshotLocked(buildSnapshotLocked(tracks_,clips_));}
void RackGraph::activate(){std::lock_guard lock(controlMutex_);for(auto& n:tracks_)n->chain->activate();master_->activate();}void RackGraph::deactivate(){std::lock_guard lock(controlMutex_);for(auto& n:tracks_)n->chain->deactivate();master_->deactivate();}void RackGraph::pauseAndResetTransport(){std::lock_guard lock(controlMutex_);writeMailboxLocked(true,false,true);}
RackGraph::State RackGraph::saveState(){std::lock_guard lock(controlMutex_);State s;for(auto& n:tracks_)s.tracks.push_back({n->volume.load(),n->inputArmed.load(),n->chain->saveChainState()});s.master=master_->saveChainState();return s;}
void RackGraph::applyGlobalMailbox() noexcept {
    const auto sequence = mailbox_.sequence.load(std::memory_order_acquire);
    if (sequence & 1U) return;
    const auto play = mailbox_.playSerial.load();
    const auto reset = mailbox_.resetSerial.load();
    const auto bpm = mailbox_.bpmSerial.load();
    const bool desiredPlaying = mailbox_.desiredPlaying.load();
    const double desiredBpm = mailbox_.desiredBpm.load();
    if (mailbox_.sequence.load(std::memory_order_acquire) != sequence) return;
    if (play != appliedPlaySerial_) { audioPlaying_ = desiredPlaying; appliedPlaySerial_ = play; }
    if (reset != appliedResetSerial_) { audioTransportFrame_ = 0; appliedResetSerial_ = reset; }
    if (bpm != appliedBpmSerial_) { audioBpm_ = desiredBpm; appliedBpmSerial_ = bpm; }
}

uint64_t RackGraph::nextBoundary(uint64_t frame,double rate,double bpm,LaunchQuantization q) noexcept {const double beats=q==LaunchQuantization::Bar?4.:q==LaunchQuantization::Quarter?1.:q==LaunchQuantization::Eighth?.5:.25;const uint64_t step=std::max<uint64_t>(1,static_cast<uint64_t>(std::llround(beats*rate*60./bpm)));return (frame/step+1)*step;}
void RackGraph::publishGlobalStatus(double rate) noexcept {statusSequence_.fetch_add(1);statusPlaying_.store(audioPlaying_);statusBpm_.store(audioBpm_);statusSamplePosition_.store(audioSamplePosition_);statusTransportFrame_.store(audioTransportFrame_);statusPositionSec_.store(static_cast<double>(audioTransportFrame_)/rate);statusSequence_.fetch_add(1,std::memory_order_release);}
void RackGraph::advanceTransport(uint32_t frames) noexcept {applyGlobalMailbox();double rate=sampleRate_.load();if(rate<=0)rate=48000.;audioSamplePosition_+=frames;if(audioPlaying_)audioTransportFrame_+=frames;publishGlobalStatus(rate);}
void RackGraph::process(const float* const* inputs,float* const* outputs,uint32_t frames) noexcept {
 GraphSnapshot* s=activeSnapshot_.load(std::memory_order_acquire);do{hazardSnapshot_.store(s,std::memory_order_seq_cst);if(s==activeSnapshot_.load(std::memory_order_acquire))break;s=activeSnapshot_.load(std::memory_order_acquire);}while(true);if(!s||frames>s->capacity||!outputs||!outputs[0]||!outputs[1]){silence(outputs,frames);hazardSnapshot_.store(nullptr,std::memory_order_seq_cst);return;} applyGlobalMailbox();double rate=sampleRate_.load();if(rate<=0)rate=48000.;double bpm=std::clamp(audioBpm_,20.,400.);double beat=audioTransportFrame_*bpm/(rate*60.);int64_t bar=static_cast<int64_t>(std::floor(beat/4.));AudioProcessContext context{audioSamplePosition_,audioTransportFrame_,0,rate,bpm,audioPlaying_,false,beat,bar,beat-bar*4.};bool masterEmpty=s->master->isEmptyForAudio(), direct=masterEmpty&&s->tracks.size()==1,mixed=false;
 for(const auto& view:s->tracks){auto& n=*view.node;auto serial=n.commandSerial.load(std::memory_order_acquire);if(serial!=n.appliedCommandSerial){n.appliedCommandSerial=serial;if(!n.desiredPlaying.load()){n.localPlaying=false;n.pendingLaunchFrame=std::numeric_limits<uint64_t>::max();}else if(audioPlaying_)n.pendingLaunchFrame=nextBoundary(audioTransportFrame_,rate,bpm,static_cast<LaunchQuantization>(n.desiredQuantization.load()));}n.localLooping=n.desiredLooping.load();float* src[2]={n.sourceLeft.data(),n.sourceRight.data()};const float* chainInput[2]={src[0],src[1]};if(view.clip){const auto& clip=*view.clip;for(uint32_t i=0;i<frames;++i){auto global=audioTransportFrame_+i;if(!audioPlaying_){n.localPlaying=false;n.pendingLaunchFrame=std::numeric_limits<uint64_t>::max();}if(n.pendingLaunchFrame!=std::numeric_limits<uint64_t>::max()&&global>=n.pendingLaunchFrame){n.localPlaying=true;n.localFrame=0;n.pendingLaunchFrame=std::numeric_limits<uint64_t>::max();}if(!n.localPlaying){src[0][i]=src[1][i]=0;continue;}double pos=n.localFrame*static_cast<double>(clip.sampleRate)/rate;if(pos>=clip.left.size()){if(n.localLooping){n.localFrame=0;pos=0;}else{n.localPlaying=false;src[0][i]=src[1][i]=0;continue;}}auto first=static_cast<size_t>(pos);auto second=std::min(first+1,clip.left.size()-1);float f=static_cast<float>(pos-first);src[0][i]=clip.left[first]+(clip.left[second]-clip.left[first])*f;src[1][i]=clip.right.empty()?src[0][i]:clip.right[first]+(clip.right[second]-clip.right[first])*f;++n.localFrame;if(!n.localLooping&&n.localFrame*static_cast<uint64_t>(clip.sampleRate)>=clip.left.size()*static_cast<uint64_t>(rate)){n.localFrame=static_cast<uint64_t>(std::ceil(clip.left.size()*rate/static_cast<double>(clip.sampleRate)));n.localPlaying=false;}else if(n.localLooping){auto bound=std::max<uint64_t>(1,static_cast<uint64_t>(std::ceil(clip.left.size()*rate/static_cast<double>(clip.sampleRate))));n.localFrame%=bound;}}}else if(n.inputArmed.load()&&inputs&&inputs[0]&&inputs[1]){chainInput[0]=inputs[0];chainInput[1]=inputs[1];}else{std::memset(src[0],0,frames*sizeof(float));std::memset(src[1],0,frames*sizeof(float));}n.statusPlaying.store(n.localPlaying);n.statusLooping.store(n.localLooping);n.statusFrame.store(n.localFrame);const float* signal[2]={chainInput[0],chainInput[1]};if(!n.chain->isEmptyForAudio()){float* out[2]={direct?outputs[0]:n.outputLeft.data(),direct?outputs[1]:n.outputRight.data()};n.chain->process(chainInput,out,frames,context);signal[0]=out[0];signal[1]=out[1];}float vol=n.volume.load();if(direct){copyScaled(outputs[0],outputs[1],signal[0],signal[1],frames,vol);continue;}if(!mixed){copyScaled(s->mixLeft.data(),s->mixRight.data(),signal[0],signal[1],frames,vol);mixed=true;}else mixScaled(s->mixLeft.data(),s->mixRight.data(),signal[0],signal[1],frames,vol);}
 if(!direct){if(!mixed){std::memset(s->mixLeft.data(),0,frames*sizeof(float));std::memset(s->mixRight.data(),0,frames*sizeof(float));}const float* mix[2]={s->mixLeft.data(),s->mixRight.data()};if(masterEmpty)copyScaled(outputs[0],outputs[1],mix[0],mix[1],frames,1);else s->master->process(mix,outputs,frames,context);}audioSamplePosition_+=frames;if(audioPlaying_)audioTransportFrame_+=frames;publishGlobalStatus(rate);hazardSnapshot_.store(nullptr,std::memory_order_seq_cst);
}
void RackGraph::reclaimerLoop(){std::unique_lock lock(reclaimerMutex_);while(!reclaimerStop_){reclaimerWake_.wait_for(lock,std::chrono::milliseconds(10));lock.unlock();reclaimRetired();lock.lock();}}
void RackGraph::reclaimRetired(){std::lock_guard lock(reclaimerMutex_);auto* hazard=hazardSnapshot_.load(std::memory_order_seq_cst);RetiredSnapshot** cursor=&retired_;while(*cursor){auto* item=*cursor;if(item->owner.get()!=hazard){*cursor=item->next;delete item;}else cursor=&item->next;}}
} // namespace guitarrackcraft
