#!/usr/bin/env bash
# Build Turnip (Mesa's open-source Adreno Vulkan driver) as a generic Khronos
# ICD (libvulkan_freedreno.so + freedreno_icd.aarch64.json) from the in-tree
# 3rd_party/mesa submodule, for arm64 Android Bionic. Replaces the Termux
# `mesa-vulkan-icd-freedreno` .deb (and the WSI-cluster of deps it dragged in).
# Phase 2 of the prebuilt→source migration. Sibling of build-mesa-zink.sh.
#
# This is the DXVK Khronos-loader FALLBACK path: the source Vulkan loader
# (build-vulkan-loader.sh) dlopens it via VK_ICD_FILENAMES → freedreno_icd.json.
# (The PRIMARY adrenotools/zink path uses the HAL driver vulkan.ad07xx.so — still
# the Termux/AdrenoTools prebuilt, Phase 3.)
#
# Key build choices (see the DT_NEEDED research):
#  -Dplatforms=        empty → NO X11/Wayland/DRI3 WSI → drops the entire
#                      libxcb*/libX11-xcb/libwayland-client/libxshmfence cluster
#                      that the Termux build linked (those are gated solely on
#                      with_platform_x11/wayland).
#  -Dfreedreno-kmds=msm,kgsl  msm = /dev/dri/renderD128 (our working DRM path,
#                      needs libdrm), kgsl = /dev/kgsl. msm keeps the one real
#                      runtime dep: libdrm (source-built by build-libdrm-android.sh).
#  -Dzstd=disabled     mesa uses zstd only for shader-cache compression → drop the
#                      dep (falls back to zlib). -static-libstdc++ drops libc++_shared.
#  => libvulkan_freedreno.so NEEDs only: libdrm.so + system libz.so/libm/libdl/libc.
#
# Output staged into toolchain/turnip-libs/ (libvulkan_freedreno.so +
# freedreno_icd.aarch64.json, library_path rewritten to the bare filename so the
# loader resolves it via LD_LIBRARY_PATH). phase_turnip then tars the asset.
#
# Run after build-libdrm-android.sh (provides toolchain/drm-android pkg-config).
# Called by scripts/build-all.sh (phase "turnip"); also runnable standalone.

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"            # vsthost_lib/
top="$(cd "$repo_root/.." && pwd)"                       # GuitarRackCraft/
M="$top/3rd_party/mesa"
PATCHES="$repo_root/patches/mesa"
STUBS="$PATCHES/build-files/android-deps-include"        # cutils/*.h, log/log.h
DRM_SYSROOT="$repo_root/toolchain/drm-android"           # source libdrm (build-libdrm-android.sh)
OUT="$repo_root/toolchain/turnip-libs"
PREFIX="$M/build-android-turnip/install"

NDK="${ANDROID_NDK:-$HOME/Android/Sdk/ndk/26.1.10909125}"
NDKBIN="$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin"
API=28

[ -d "$M/.git" ] || [ -f "$M/.git" ] || { echo "error: mesa submodule not at $M — git submodule update --init --recursive 3rd_party/mesa" >&2; exit 1; }
[ -f "$DRM_SYSROOT/lib/pkgconfig/libdrm.pc" ] || { echo "error: source libdrm not at $DRM_SYSROOT — run build-libdrm-android.sh first" >&2; exit 1; }
[ -x "$NDKBIN/aarch64-linux-android$API-clang" ] || { echo "error: NDK not at $NDK (set ANDROID_NDK)" >&2; exit 1; }
for t in meson ninja patchelf; do command -v "$t" >/dev/null || { echo "error: $t not on PATH" >&2; exit 1; }; done

echo "=== Turnip Vulkan ICD (libvulkan_freedreno.so, no-WSI, msm+kgsl) ==="
echo "    mesa: $(git -C "$M" describe --tags 2>/dev/null || echo '?')"

# Reset the shared mesa submodule (build-mesa-zink may have left patch 0001 +
# .android-deps applied); preserve both build dirs so a zink rerun stays
# incremental. Turnip uses NO mesa source patch (the zink patch 0001 is
# desktop-GL-specific) and gets libdrm from the source sysroot, not .android-deps.
echo "[+] reset mesa submodule (preserve build dirs)"
git -C "$M" reset --hard HEAD >/dev/null
git -C "$M" clean -fdx -e build-android-zink -e build-android-turnip -e .android-deps >/dev/null

# Two Bionic build fixes for the freedreno Vulkan ICD (NOT needed by the zink
# build, which compiles no Vulkan driver):
#  - detect_os.h MESA_FORCE_LINUX escape hatch → with -DMESA_FORCE_LINUX below,
#    DETECT_OS_ANDROID=0, so turnip's Android AHardwareBuffer/gralloc/VNDK code
#    (tu_device/knl/formats/image, needs <vndk/hardware_buffer.h> the NDK lacks)
#    is compiled out → a generic Linux ICD.
#  - drop the VK_KHR_display WSI on Android hosts: wsi_common_display.c uses
#    pthread_cancel/PTHREAD_CANCEL_ASYNCHRONOUS, which Bionic doesn't have, and it
#    is built whenever msm enables KMS/DRM. We render off-screen for DXVK and
#    never use direct-KMS display, so exclude it (meson, keyed on host==android).
echo "[+] apply patch 0002 (MESA_FORCE_LINUX hatch + drop VK_KHR_display WSI on Bionic)"
git -C "$M" apply "$PATCHES/0002-turnip-icd-bionic-no-display-wsi.patch"

CROSS="$M/android-turnip-aarch64.ini"
cat > "$CROSS" <<EOF
# AUTO-GENERATED by build-turnip-icd.sh — machine-local paths. Do not commit.
[binaries]
c = '$NDKBIN/aarch64-linux-android$API-clang'
cpp = '$NDKBIN/aarch64-linux-android$API-clang++'
ar = '$NDKBIN/llvm-ar'
strip = '$NDKBIN/llvm-strip'
c_ld = 'lld'
cpp_ld = 'lld'
pkg-config = ['env', 'PKG_CONFIG_LIBDIR=$DRM_SYSROOT/lib/pkgconfig', 'pkg-config']

[host_machine]
system = 'android'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'

[properties]
needs_exe_wrapper = true

[built-in options]
c_args = ['-I$STUBS', '-D__USE_GNU', '-DMESA_FORCE_LINUX']
cpp_args = ['-I$STUBS', '-D__USE_GNU', '-DMESA_FORCE_LINUX']
c_link_args = ['-static-libstdc++', '-llog']
cpp_link_args = ['-static-libstdc++', '-llog']
EOF

B="$M/build-android-turnip"
echo "[+] meson setup (vulkan-drivers=freedreno, platforms empty, zstd disabled)"
rm -rf "$B"
meson setup "$B" "$M" --cross-file "$CROSS" \
  --buildtype=release --default-library=shared --prefix="$PREFIX" \
  -Dvulkan-drivers=freedreno -Dgallium-drivers= -Dplatforms= \
  -Dfreedreno-kmds=msm,kgsl \
  -Degl=disabled -Dgbm=disabled -Dglx=disabled -Dglvnd=disabled \
  -Dopengl=false -Dgles1=disabled -Dgles2=disabled \
  -Ddri3=disabled -Dllvm=disabled -Dshared-glapi=disabled \
  -Dxmlconfig=disabled -Dvulkan-layers= -Dvalgrind=disabled \
  -Dlibunwind=disabled -Dandroid-stub=false -Dzstd=disabled \
  -Db_ndebug=true

echo "[+] ninja install"
ninja -C "$B" >/dev/null
rm -rf "$PREFIX"
ninja -C "$B" install >/dev/null

# --- stage the ICD + manifest into the turnip asset dir --------------------
ICD_SO="$PREFIX/lib/libvulkan_freedreno.so"
ICD_JSON="$(ls "$PREFIX"/share/vulkan/icd.d/freedreno_icd*.json 2>/dev/null | head -1)"
[ -f "$ICD_SO" ]   || { echo "error: build produced no libvulkan_freedreno.so" >&2; exit 1; }
[ -f "$ICD_JSON" ] || { echo "error: build produced no freedreno_icd json" >&2; exit 1; }
mkdir -p "$OUT"
cp -f "$ICD_SO" "$OUT/libvulkan_freedreno.so"
"$NDKBIN/llvm-strip" --strip-unneeded "$OUT/libvulkan_freedreno.so"
cp -f "$ICD_JSON" "$OUT/freedreno_icd.aarch64.json"
# Rewrite library_path to the bare filename so the Khronos loader resolves it via
# LD_LIBRARY_PATH (the extracted turnip dir at runtime), not mesa's install path.
python3 - "$OUT/freedreno_icd.aarch64.json" <<'PY'
import json,sys
p=sys.argv[1]; d=json.load(open(p)); d["ICD"]["library_path"]="libvulkan_freedreno.so"
json.dump(d,open(p,"w"),indent=4)
PY

# --- verify: ICD entrypoint + Bionic-clean + WSI cluster gone --------------
RE="$NDKBIN/llvm-readelf"
F="$OUT/libvulkan_freedreno.so"
needed="$("$RE" -d "$F" | awk -F'[][]' '/NEEDED/{print $2}' | tr '\n' ' ')"
badver="$("$RE" -V "$F" 2>/dev/null | grep -oE 'GLIBC_[0-9.]+|ZLIB_[0-9.]+' | sort -u | tr '\n' ' ' || true)"
icdsym="$("$RE" --dyn-syms "$F" | grep -cE 'vk_icdGetInstanceProcAddr' || true)"
wsi="$(echo "$needed" | grep -coE 'libxcb|libX11|libwayland|libxshmfence|libandroid-shmem' || true)"
echo
echo "[=] $F ($(du -h "$F" | cut -f1))"
echo "    NEEDED: $needed"
echo "    vk_icdGetInstanceProcAddr: $icdsym   WSI-cluster NEEDED: $wsi"
fail=0
[ "$icdsym" -ge 1 ] || { echo "FAIL: not a Khronos ICD (no vk_icdGetInstanceProcAddr)" >&2; fail=1; }
[ -z "$badver" ]    || { echo "FAIL: non-Bionic verneeds: $badver" >&2; fail=1; }
[ "$wsi" -eq 0 ]    || { echo "FAIL: WSI deps still linked (platforms not empty?)" >&2; fail=1; }
[ "$fail" -eq 0 ] || exit 1

# Leave the shared mesa submodule SOURCE clean (revert patch 0002 — the build
# output is already staged). The CI assemble job runs this before build.sh's
# cmake X11-sysroot mesa, which uses the same checkout + applies its own
# detect_os sed; pristine source avoids any cross-consumer interference.
git -C "$M" checkout -- src/util/detect_os.h src/vulkan/meson.build src/vulkan/wsi/meson.build 2>/dev/null || true
echo "[=] OK — source Turnip ICD staged for turnip-libs.tar.gz"
