#!/usr/bin/env bash
# Generates a tiny STUB libLLVM.so that exports exactly the LLVM-C symbols
# Mesa's libgallium imports (~220, all @LLVM_21.1), as no-op functions + dummy
# data objects. See fetch-mesa-zink-libs.sh for WHY (zink never calls LLVM; this
# replaces the real 133MB non-Bionic-clean libLLVM). A call into any stub is made
# LOUD (writes to stderr) so we learn if zink unexpectedly hits the LLVM path.
set -euo pipefail
repo_root="$(cd "$(dirname "$0")/.." && pwd)"
cd "$repo_root"

out="toolchain/mesa-zink-libs"
NDK="${ANDROID_NDK:-$HOME/Android/Sdk/ndk/26.1.10909125}"
RE="$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-readelf"
CC="$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang"

gallium=$(ls "$out"/libgallium-*.so 2>/dev/null | head -1)
[ -z "$gallium" ] && gallium=$(ls "$repo_root"/.cache/mesa-inspect/data/data/com.termux/files/usr/lib/libgallium-*.so 2>/dev/null | head -1)
[ -n "$gallium" ] || { echo "error: libgallium not found (run fetch first)"; exit 1; }
echo "[+] deriving LLVM imports from $(basename "$gallium")"

ver=$("$RE" --dyn-syms "$gallium" 2>/dev/null | awk '$7=="UND" && $8 ~ /@LLVM_/{sub(/.*@/,"",$8);print $8}' | sort -u | head -1)
[ -n "$ver" ] || { echo "error: no @LLVM_ version found"; exit 1; }
echo "[+] LLVM symbol version: $ver"

"$RE" --dyn-syms "$gallium" 2>/dev/null | awk '$7=="UND" && $8 ~ /@LLVM_/ && $4=="FUNC"{sub(/@.*/,"",$8);print $8}' | sort -u > /tmp/_llvm_func.txt
"$RE" --dyn-syms "$gallium" 2>/dev/null | awk '$7=="UND" && $8 ~ /@LLVM_/ && $4=="OBJECT"{sub(/@.*/,"",$8);print $8}' | sort -u > /tmp/_llvm_data.txt
echo "[+] funcs=$(wc -l </tmp/_llvm_func.txt) data=$(wc -l </tmp/_llvm_data.txt)"

{
  echo '/* AUTO-GENERATED by build-llvm-stub.sh — do not edit. Stub libLLVM.so:'
  echo ' * satisfies libgallium-zinks vestigial libLLVM NEEDED without the real'
  echo ' * 133MB driver. A call here = zink hit the LLVM path unexpectedly. */'
  echo '#include <unistd.h>'
  echo '__attribute__((visibility("hidden"))) static void vstpoc_llvm_stub(const char*n){'
  echo '  (void)write(2,"VSTPOC: stub libLLVM called: ",29); (void)write(2,n,__builtin_strlen(n)); (void)write(2,"\n",1); }'
  # A few LLVM-C calls in gallium's init path must report SUCCESS or gallium
  # aborts screen creation (zink then has no EGL display). These are harmless
  # threading-init probes; return 1 (success/yes) instead of the default 0.
  while read s; do
    case "$s" in
      LLVMStartMultithreaded|LLVMIsMultithreaded|LLVMContextShouldDiscardValueNames)
        echo "long $s(void){ return 1; }" ;;
      *)
        echo "long $s(void){ vstpoc_llvm_stub(\"$s\"); return 0; }" ;;
    esac
  done < /tmp/_llvm_func.txt
  while read s; do echo "char $s[64] = {0};"; done < /tmp/_llvm_data.txt
} > "$out/llvm_stub.c"

{ echo "$ver {"; echo '  global:'; cat /tmp/_llvm_func.txt /tmp/_llvm_data.txt | sed 's/$/;/'; echo '  local: *;'; echo '};'; } > "$out/llvm_stub.ver"

"$CC" -shared -fPIC -O2 -o "$out/libLLVM.so" "$out/llvm_stub.c" \
   -Wl,--version-script="$out/llvm_stub.ver" -Wl,-soname,libLLVM.so
echo "[+] stub libLLVM.so: $(stat -c%s "$out/libLLVM.so") bytes ($(wc -l </tmp/_llvm_func.txt) stubs, ver $ver)"
