#!/usr/bin/env bash
# Build the Mesa-Zink desktop-GL libs (GL 4.x over Vulkan/Turnip) that give
# wine's win32u a real desktop-GL context for JUCE GL plugin editors (AmpliTube,
# LeCto, WagnerSharp, ...). Without these the GL plugins crash vst_host with
# "libEGL fatal: did not find extension DRI_SWRast version 5".
#
# Output: vsthost_lib/src/main/assets/mesa-zink-libs.tar.gz (extracted at
# runtime by WineSetup.extractMesaZinkLibs, gated on SETUP_VERSION). The libs
# also land in vsthost_lib/toolchain/mesa-zink-libs/ (the staging dir).
#
# Self-contained + machine-portable: applies patches/mesa/0001, drops the
# captured header stubs (cutils/log) into the submodule, links the SOURCE libdrm
# (toolchain/drm-android, built by build-libdrm-android.sh — no checked-in blob), and
# GENERATES the meson cross-file with this machine's NDK + repo paths (the
# committed build-files/android-aarch64.ini has hardcoded paths, used only as a
# reference). Run after `git submodule update --init --recursive 3rd_party/mesa`.
#
# Called by scripts/build-all.sh (step "build-mesa-zink"); also runnable alone.
# See patches/mesa/README.md and project_zink_layer3_state for the full history.

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"            # vsthost_lib/
top="$(cd "$repo_root/.." && pwd)"                       # GuitarRackCraft/
M="$top/3rd_party/mesa"
PATCHES="$repo_root/patches/mesa"
OUT="$repo_root/toolchain/mesa-zink-libs"

NDK="${ANDROID_NDK:-$HOME/Android/Sdk/ndk/26.1.10909125}"
NDKBIN="$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin"

[ -d "$M/.git" ] || [ -f "$M/.git" ] || {
    echo "error: mesa submodule not at $M — run: git submodule update --init --recursive 3rd_party/mesa" >&2
    exit 1
}
[ -x "$NDKBIN/aarch64-linux-android28-clang" ] || {
    echo "error: NDK not found at $NDK (set ANDROID_NDK)" >&2; exit 1; }
for t in meson ninja patchelf; do command -v "$t" >/dev/null || { echo "error: $t not on PATH" >&2; exit 1; }; done

echo "[+] mesa submodule reset + apply patches/mesa/0001 + 0003"
git -C "$M" reset --hard HEAD >/dev/null
git -C "$M" clean -fdx -e build-android-zink -e build-android-turnip -e build-android-lavapipe -e .android-deps >/dev/null
git -C "$M" apply "$PATCHES/0001-zink-android-desktop-gl-via-turnip.patch"
# 0003: let zink accept a software (CPU) device — needed so the GL editor renders
# on lavapipe (the universal software-Vulkan fallback). Upstream gates this on
# LIBGL_ALWAYS_SOFTWARE, which doesn't reach the editor's wine process; harmless on
# the Turnip path (a real GPU is never CPU-typed). See feedback_lavapipe_*.
git -C "$M" apply "$PATCHES/0003-zink-accept-cpu-device.patch"

echo "[+] drop captured header stubs (cutils/log) into the submodule"
DEPS="$M/.android-deps"
rm -rf "$DEPS"
mkdir -p "$DEPS/include"
cp -r "$PATCHES/build-files/android-deps-include/." "$DEPS/include/"
# libdrm (its .so + headers + .pc + libsync.h) now comes from the SOURCE build
# (build-libdrm-android.sh → toolchain/drm-android), not a checked-in Termux blob.
# Phase 2/A3 of the prebuilt→source migration. phase_mesa runs build-libdrm first.
DRM_SYSROOT="$repo_root/toolchain/drm-android"
[ -f "$DRM_SYSROOT/lib/pkgconfig/libdrm.pc" ] || {
    echo "error: source libdrm not at $DRM_SYSROOT — run build-libdrm-android.sh first" >&2; exit 1; }

echo "[+] generate machine-local meson cross-file"
CROSS="$M/android-aarch64.ini"
cat > "$CROSS" <<EOF
# AUTO-GENERATED by build-mesa-zink.sh — machine-local paths. Do not commit.
[binaries]
c = '$NDKBIN/aarch64-linux-android28-clang'
cpp = '$NDKBIN/aarch64-linux-android28-clang++'
ar = '$NDKBIN/llvm-ar'
strip = '$NDKBIN/llvm-strip'
c_ld = 'lld'
cpp_ld = 'lld'
pkg-config = ['env', 'PKG_CONFIG_LIBDIR=$DRM_SYSROOT/lib/pkgconfig', 'pkg-config']

[host_machine]
system = 'android'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'

[properties]
needs_exe_wrapper = true

[built-in options]
c_args = ['-I$DEPS/include', '-fno-omit-frame-pointer', '-funwind-tables']
cpp_args = ['-I$DEPS/include', '-fno-omit-frame-pointer', '-funwind-tables']
c_link_args = ['-static-libstdc++', '-llog', '-lsync']
cpp_link_args = ['-static-libstdc++', '-llog', '-lsync']
EOF

B="$M/build-android-zink"
echo "[+] meson setup (zink-only, no glvnd, no llvm, standalone libEGL)"
rm -rf "$B"
meson setup "$B" "$M" --cross-file "$CROSS" \
  -Dgallium-drivers=zink -Dvulkan-drivers= -Dglvnd=false -Dllvm=disabled \
  -Dplatforms= -Degl=enabled -Dgbm=enabled -Dglx=disabled -Dgles2=enabled \
  -Dgles1=disabled -Dshared-glapi=enabled -Ddri3=disabled

echo "[+] ninja (default targets — builds libgallium-<ver>/libEGL/libgbm/libglapi/libexpat;"
echo "    naming the version-specific gallium target explicitly is brittle across mesa bumps)"
ninja -C "$B"

echo "[+] build Turnip Vulkan shim (zink dlsyms vkGet{Instance,Device}ProcAddr)"
"$NDKBIN/aarch64-linux-android28-clang" -shared -fPIC -fvisibility=hidden \
  -Wl,-soname,libvulkan_vstpoc.so \
  "$repo_root/src/main/cpp/mesashim/vulkan_turnip_shim.c" -o /tmp/libvulkan_vstpoc.so

echo "[+] stage into $OUT"
mkdir -p "$OUT/dri"
GALLIUM="$(ls "$B"/src/gallium/targets/dri/libgallium*.so | head -1)"
cp "$GALLIUM"                                         "$OUT/$(basename "$GALLIUM")"
cp "$GALLIUM"                                         "$OUT/dri/zink_dri.so"   # zink_dri = libgallium
cp "$B/src/egl/libEGL.so"                             "$OUT/libEGL_vstpoc.so"
cp "$B/src/gbm/libgbm.so"                             "$OUT/libgbm.so"
cp "$B/src/mapi/shared-glapi/libglapi.so"             "$OUT/libglapi.so"
cp "$(ls "$B"/subprojects/expat-*/libexpat.so | head -1)" "$OUT/libexpat.so"   # mesa-built expat subproject
cp -L "$DRM_SYSROOT/lib/libdrm.so"                    "$OUT/libdrm.so"    # source libdrm (build-libdrm-android.sh)
cp /tmp/libvulkan_vstpoc.so                           "$OUT/libvulkan_vstpoc.so"

# Strip the mesa-built libs (ninja leaves them with full debug info → ~83MB
# libgallium). --strip-unneeded keeps the dynamic/exported symbols (verified:
# __driDriverGetExtensions_zink survives) → ~15.7MB, matching the shipped asset.
# libEGL_vstpoc is left UNSTRIPPED (the working asset shipped it at ~3.8MB;
# --strip-unneeded over-strips it). libdrm/libvulkan_vstpoc are already small.
echo "[+] strip the mesa-built libs (--strip-unneeded; libEGL left as built)"
( cd "$OUT" && for so in libgallium-*.so dri/zink_dri.so libgbm.so libexpat.so libglapi.so; do
    [ -f "$so" ] && "$NDKBIN/llvm-strip" --strip-unneeded "$so"
done )

echo "[+] patchelf soname + neutralise verneed on libEGL (Bionic rejects it otherwise)"
patchelf --set-soname libEGL_vstpoc.so "$OUT/libEGL_vstpoc.so"
python3 - "$OUT/libEGL_vstpoc.so" <<PY
import importlib.util as u, sys
from pathlib import Path
s = u.spec_from_file_location("p", "$repo_root/scripts/pack-wine-fex.py")
m = u.module_from_spec(s); s.loader.exec_module(m)
m.strip_symbol_versions(Path(sys.argv[1]))
PY

echo "[+] tar → src/main/assets/mesa-zink-libs.tar.gz"
mkdir -p "$repo_root/src/main/assets"   # may not exist on a fresh clone (gitignored)
( cd "$OUT" && tar czf - libgbm.so libexpat.so libdrm.so libvulkan_vstpoc.so \
    libglapi.so "$(basename "$GALLIUM")" libEGL_vstpoc.so dri/zink_dri.so ) \
  > "$repo_root/src/main/assets/mesa-zink-libs.tar.gz"

echo "[=] mesa-zink built. asset: $(du -h "$repo_root/src/main/assets/mesa-zink-libs.tar.gz" | cut -f1)"
echo "    (if the lib set changed, bump WineSetup SETUP_VERSION so a clean install re-extracts)"
