#!/usr/bin/env bash
# Build Turnip (Mesa's Adreno Vulkan driver) as an ANDROID HAL driver
# (vulkan.ad07xx.so, exports HMI = hw_module_t HAL_MODULE_INFO_SYM) from the
# in-tree 3rd_party/mesa submodule, for arm64 Android Bionic. Replaces the
# AdrenoTools prebuilt (K11MCH1 Turnip_v26.0.0_R8.zip) that fetch-turnip-libs.sh
# downloads. Phase 3 (final) of the prebuilt→source migration.
#
# This is the PRIMARY GPU path: libadrenotools (a Winlator-style linker-namespace
# hook) dlopens this HAL to give the driver /dev/kgsl access on untrusted_app
# (where renderD128/DRM is SELinux-denied). Mesa-Zink's desktop GL (JUCE GL
# editors — AmpliTube/LeCto) goes ONLY through this path. The HAL form is what
# exports HMI (vs the Khronos ICD form from build-turnip-icd.sh, which exports
# vk_icd* for the DXVK loader fallback path).
#
# Key build choices (vs the ICD build):
#  -Dplatforms=android        builds tu_android.cc → exports HMI (the HAL module).
#  -Dandroid-stub=true        supplies ALL Android headers from mesa's in-tree
#                             include/android_stub/ (vndk/hardware_buffer.h,
#                             hardware/hardware.h+hwvulkan.h, cutils/log/sync/
#                             nativewindow) AND builds stub .so's for the link.
#                             The real platform libs come from the adrenotools
#                             namespace at runtime (DT_NEEDED stays on them).
#  -Dplatform-sdk-version=34  load-bearing: <26 disables the AHardwareBuffer path
#                             (vk_android.c #if ANDROID_API_LEVEL>=26). 34 = Android 14.
#  -Dfreedreno-kmds=kgsl      /dev/kgsl on stock OnePlus → no libdrm dep (matches R8).
#  NO MESA_FORCE_LINUX, NO patch 0002: the HAL NEEDS DETECT_OS_ANDROID=1 (for
#  tu_android.cc), and platforms=android already excludes the VK_KHR_display WSI.
#  NO cutils/log -I stubs: android-stub provides them (adding -I would collide).
#
# Output: toolchain/turnip-libs/vulkan.ad07xx.so (the soname WineHostProcess sets
# as VSTPOC_ADRENOTOOLS_DRIVERNAME). phase_turnip tars it into turnip-libs.tar.gz.
#
# Called by scripts/build-all.sh (phase "turnip"); also runnable standalone.

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/.." && pwd)"            # vsthost_lib/
top="$(cd "$repo_root/.." && pwd)"                       # GuitarRackCraft/
M="$top/3rd_party/mesa"
OUT="$repo_root/toolchain/turnip-libs"
PREFIX="$M/build-android-turnip-hal/install"

NDK="${ANDROID_NDK:-$HOME/Android/Sdk/ndk/26.1.10909125}"
NDKBIN="$NDK/toolchains/llvm/prebuilt/linux-x86_64/bin"
API=34                                                   # clang minSdk: AHardwareBuffer symbols (>=26) + matches platform-sdk-version

[ -d "$M/.git" ] || [ -f "$M/.git" ] || { echo "error: mesa submodule not at $M — git submodule update --init --recursive 3rd_party/mesa" >&2; exit 1; }
[ -x "$NDKBIN/aarch64-linux-android$API-clang" ] || { echo "error: NDK has no aarch64-linux-android$API-clang at $NDK" >&2; exit 1; }
for t in meson ninja; do command -v "$t" >/dev/null || { echo "error: $t not on PATH" >&2; exit 1; }; done

echo "=== Turnip Android HAL (vulkan.ad07xx.so, exports HMI, kgsl) ==="
echo "    mesa: $(git -C "$M" describe --tags 2>/dev/null || echo '?')   NDK API: $API"

# The HAL build uses pristine mesa source (NO patch — android-stub + system=android
# give it everything). Reset to drop any zink/turnip-icd patch left applied;
# preserve the other build dirs so their re-runs stay incremental.
echo "[+] reset mesa submodule (preserve build dirs)"
git -C "$M" reset --hard HEAD >/dev/null
git -C "$M" clean -fdx -e build-android-zink -e build-android-turnip -e build-android-turnip-hal -e .android-deps >/dev/null

CROSS="$M/android-turnip-hal-aarch64.ini"
cat > "$CROSS" <<EOF
# AUTO-GENERATED by build-turnip-hal.sh — machine-local paths. Do not commit.
[binaries]
c = '$NDKBIN/aarch64-linux-android$API-clang'
cpp = '$NDKBIN/aarch64-linux-android$API-clang++'
ar = '$NDKBIN/llvm-ar'
strip = '$NDKBIN/llvm-strip'
c_ld = 'lld'
cpp_ld = 'lld'

[host_machine]
system = 'android'
cpu_family = 'aarch64'
cpu = 'aarch64'
endian = 'little'

[properties]
needs_exe_wrapper = true

[built-in options]
c_args = ['-D__USE_GNU']
cpp_args = ['-D__USE_GNU']
c_link_args = ['-static-libstdc++']
cpp_link_args = ['-static-libstdc++']
EOF

B="$M/build-android-turnip-hal"
echo "[+] meson setup (platforms=android, android-stub, sdk=34, kgsl)"
rm -rf "$B"
meson setup "$B" "$M" --cross-file "$CROSS" \
  --buildtype=release --default-library=shared --prefix="$PREFIX" \
  -Dplatforms=android -Dandroid-stub=true -Dplatform-sdk-version=34 \
  -Dandroid-libbacktrace=disabled \
  -Dvulkan-drivers=freedreno -Dgallium-drivers= -Dfreedreno-kmds=kgsl \
  -Degl=disabled -Dgbm=disabled -Dglx=disabled -Dopengl=false \
  -Dgles1=disabled -Dgles2=disabled -Dllvm=disabled -Dshared-glapi=disabled \
  -Dvulkan-layers= -Dvalgrind=disabled -Dlibunwind=disabled \
  -Db_ndebug=true

echo "[+] ninja"
ninja -C "$B" >/dev/null

# The HAL .so is libvulkan_freedreno.so in the build tree; stage it under the
# adrenotools driver name. (install isn't needed — grab from the build dir.)
HAL_SO="$B/src/freedreno/vulkan/libvulkan_freedreno.so"
[ -f "$HAL_SO" ] || { echo "error: build produced no libvulkan_freedreno.so (HAL)" >&2; exit 1; }
mkdir -p "$OUT"
cp -f "$HAL_SO" "$OUT/vulkan.ad07xx.so"
"$NDKBIN/llvm-strip" --strip-unneeded "$OUT/vulkan.ad07xx.so"

# --- verify: exports HMI (HAL form) + Bionic-clean + platform DT_NEEDED --------
RE="$NDKBIN/llvm-readelf"
F="$OUT/vulkan.ad07xx.so"
hmi="$("$RE" --dyn-syms "$F" | grep -cE ' HMI$' || true)"
needed="$("$RE" -d "$F" | awk -F'[][]' '/NEEDED/{print $2}' | tr '\n' ' ')"
badver="$("$RE" -V "$F" 2>/dev/null | grep -oE 'GLIBC_[0-9.]+|ZLIB_[0-9.]+' | sort -u | tr '\n' ' ' || true)"
echo
echo "[=] $F ($(du -h "$F" | cut -f1))"
echo "    exports HMI: $hmi   NEEDED: $needed"
fail=0
[ "$hmi" -ge 1 ] || { echo "FAIL: does not export HMI — not a HAL build (adrenotools would reject it)" >&2; fail=1; }
[ -z "$badver" ] || { echo "FAIL: non-Bionic verneeds: $badver" >&2; fail=1; }
echo "$needed" | grep -q 'libhardware.so' || { echo "FAIL: missing libhardware (not the HAL link)" >&2; fail=1; }
[ "$fail" -eq 0 ] || exit 1

# Leave the shared mesa submodule SOURCE clean (it was pristine; reset is a no-op
# but keep parity with build-turnip-icd's self-contained behavior).
git -C "$M" checkout -- . 2>/dev/null || true
echo "[=] OK — source Turnip HAL staged as vulkan.ad07xx.so"
